[[beans-factory-method-injection]]
= 方法注入

在大多数应用场景中，container 中的大多数 bean 都是 xref:core/beans/factory-scopes.adoc#beans-factory-scopes-singlet
on[singletons]。当
单例 bean 需要与另一个单例 bean 协作，或非单例 bean
需要与另一个非单例 bean 协作时，通常通过将一个 bean 定义为另一个 bean 的属性来处理依赖关系。当 bean
的生命周期不同时，问题就出现了。假设单例 bean A 需要使用非单例（原型）bean B，可能是在 A
的每次方法调用时。container 只创建单例 bean A
一次，因此只有一次机会设置属性。container 无法在每次需要时为 bean A 提供一个新的 bean B 实例。

一种解决方案是放弃部分控制反转。你可以通过实现 `ApplicationContextAware` 接口，让
xref:core/beans/factory-nature.adoc#beans-factory-aware[Bean A 感知容器]，并在每次 Bean A 需要时，通过
xref:core/beans/basics.adoc#beans-factory-client[向容器发起 `getBean("B")` 调用]来获取（通常是新的）Bean B
实例。下面的示例展示了这一做法：
[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",chomp="-packages",fold="none"]
----
	package fiona.apple;

	// Spring-API imports
	import org.springframework.beans.BeansException;
	import org.springframework.context.ApplicationContext;
	import org.springframework.context.ApplicationContextAware;

	/**
	 * 使用有状态的 Command 风格类来执行某些处理的类。
	 */
	public class CommandManager implements ApplicationContextAware {

		private ApplicationContext applicationContext;

		public Object process(Map commandState) {
			// 获取相应 `Command` 的新实例。
			Command command = createCommand();
			// 在（希望是全新的）`Command` 实例上设置状态。
			command.setState(commandState);
			return command.execute();
		}

		protected Command createCommand() {
			// 注意 Spring API 依赖！
			return this.applicationContext.getBean("command", Command.class);
		}

		public void setApplicationContext(
				ApplicationContext applicationContext) throws BeansException {
			this.applicationContext = applicationContext;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",chomp="-packages",fold="none"]
----
	package fiona.apple

	// Spring-API imports
	import org.springframework.context.ApplicationContext
	import org.springframework.context.ApplicationContextAware

	// A class that uses a stateful Command-style class to perform
	// some processing.
	class CommandManager : ApplicationContextAware {

		private lateinit var applicationContext: ApplicationContext

		fun process(commandState: Map<*, *>): Any {
			// grab a new instance of the appropriate Command
			val command = createCommand()
			// set the state on the (hopefully brand new) Command instance
			command.state = commandState
			return command.execute()
		}

		// notice the Spring API dependency!
		protected fun createCommand() =
				applicationContext.getBean("command", Command::class.java)

		override fun setApplicationContext(applicationContext: ApplicationContext) {
			this.applicationContext = applicationContext
		}
	}
----
======

上述做法并不可取，因为业务代码会感知并耦合到
Spring 框架。方法注入是 Spring IoC 容器的一项较为高级的特性，可让你干净利落地处理这种用例。

****
你可以在{spring-site-blog}/2004/08/06/method-injection/[这篇博客文章]中了解更多关于方法注入的动机。
****


[[beans-factory-lookup-method-injection]]
== 查找方法注入

查找方法注入是指容器能够覆盖容器管理 Bean 上的方法，并返回容器中另一个指定 Bean 的查找结果。这种查找通常涉及原型
Bean，正如 xref:core/beans/dependencies/factory-method-injection.adoc[上一节] 所描述的场景。Spring 框架通过使用 CGLIB 库生成字节码，动态创建覆盖该方法的子类，从而实现这种方法注入。

[NOTE]
====
* 要使这种动态子类化生效，Spring Bean 容器所子类化的类不能是 `final`，且待重写的方法也不能是 `final`。
* 对包含 `abstract` 方法的类进行单元测试时，需要自行对该类进行子类化，并为 `abstract` 方法提供桩实现。
* 另一个关键限制是，查找方法无法与工厂方法配合使用，尤其不适用于配置类中的 `@Bean`
方法，因为在这种情况下，容器并不负责创建实例，因此无法在运行时动态生成子类。
====

在前一个代码片段中的 `CommandManager` 类的情况下，Spring
容器会动态覆盖 `createCommand()` 方法的实现。`CommandManager` 类没有任何 Spring 依赖，正如
重新修改后的示例所示：
[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",chomp="-packages",fold="none"]
----
	package fiona.apple;

	// 不再需要 Spring 导入！

	public abstract class CommandManager {

		public Object process(Object commandState) {
			// 获取相应 `Command` 接口的新实例
			Command command = createCommand();
			// 在（希望是全新的）`Command` 实例上设置状态
			command.setState(commandState);
			return command.execute();
		}

		// 好的……但这个方法的具体实现在哪里？
		protected abstract Command createCommand();
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes",chomp="-packages",fold="none"]
----
	package fiona.apple

	// 不再需要 Spring 导入！

	abstract class CommandManager {

		fun process(commandState: Any): Any {
			// 获取相应 `Command` 接口的新实例
			val command = createCommand()
			// 在（希望是全新的）`Command` 实例上设置状态
			command.state = commandState
			return command.execute()
		}

		// 好的……但这个方法的具体实现在哪里？
		protected abstract fun createCommand(): Command
	}
----
======

在包含待注入方法的客户端类中（本例中的 `CommandManager`），待注入方法需要具有以下形式的签名：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<public|protected> [abstract] <return-type> theMethodName(no-arguments);
----

如果方法是 `abstract`，动态生成的子类会实现该方法。
否则，动态生成的子类会覆盖原始类中定义的具体方法。请看以下示例：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<!-- 以原型（非单例）方式部署的有状态 Bean-->
	<bean id="myCommand" class="fiona.apple.AsyncCommand" scope="prototype">
		<!-- 在此处按需注入依赖 -->
	</bean>

	<!-- commandManager 使用 myCommand 原型 Bean -->
	<bean id="commandManager" class="fiona.apple.CommandManager">
		<lookup-method name="createCommand" bean="myCommand"/>
	</bean>
----

标识为 `commandManager` 的 Bean 在每次需要 `myCommand` Bean 的新实例时，都会调用自身的 `createCommand()`
方法。如果确实需要原型作用域，则必须将 `myCommand` Bean 部署为原型。如果它是
xref:core/beans/factory-scopes.adoc#beans-factory-scopes-singleton[单例]，那么每次返回的都是 `myCommand` Bean
的同一个实例。

另外，在基于注解的组件模型中，可以通过 `@Lookup` 注解来声明查找方法，如下例所示：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes"]
----
	public abstract class CommandManager {

		public Object process(Object commandState) {
			Command command = createCommand();
			command.setState(commandState);
			return command.execute();
		}

		@Lookup("myCommand")
		protected abstract Command createCommand();
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes"]
----
	abstract class CommandManager {

		fun process(commandState: Any): Any {
			val command = createCommand()
			command.state = commandState
			return command.execute()
		}

		@Lookup("myCommand")
		protected abstract fun createCommand(): Command
	}
----
======

或者，更惯用的做法是，你可以依赖目标 Bean 根据查找方法声明的返回类型来解析。

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes"]
----
	public abstract class CommandManager {

		public Object process(Object commandState) {
			Command command = createCommand();
			command.setState(commandState);
			return command.execute();
		}

		@Lookup
		protected abstract Command createCommand();
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes"]
----
	abstract class CommandManager {

		fun process(commandState: Any): Any {
			val command = createCommand()
			command.state = commandState
			return command.execute()
		}

		@Lookup
		protected abstract fun createCommand(): Command
	}
----
======

[TIP]
====
访问不同作用域目标 Bean 的另一种方式是通过 `ObjectFactory`/`Provider` 注入点。请参阅
xref:core/beans/factory-scopes.adoc#beans-factory-scopes-other-injection[将作用域 Bean 作为依赖项]。

您可能还会发现 `ServiceLocatorFactoryBean`（位于 `org.springframework.beans.factory.config` 包中）很有用。
====


[[beans-factory-arbitrary-method-replacement]]
== 任意方法替换

方法注入中，比查找方法注入实用性稍逊的一种形式，是能够用另一个方法实现来替换受管 Bean
中的任意方法。在真正需要此功能之前，你可以放心跳过本节其余内容。

使用基于 XML 的配置元数据时，你可以利用 `replaced-method` 元素，为已部署的 Bean
替换现有方法实现。考虑以下类，其中有一个名为 `computeValue` 的方法，我们希望将其覆盖：
[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes"]
----
	public class MyValueCalculator {

		public String computeValue(String input) {
			// some real code...
		}

		// some other methods...
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes"]
----
	class MyValueCalculator {

		fun computeValue(input: String): String {
			// some real code...
		}

		// some other methods...
	}
----
======

实现 `org.springframework.beans.factory.support.MethodReplacer` 接口的类提供了新方法的定义，如下例所示：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes"]
----
	/**
	 * 该内容旨在用于覆盖 `MyValueCalculator` 中现有的 `computeValue(String)` 实现。
	 */
	public class ReplacementComputeValue implements MethodReplacer {

		public Object reimplement(Object o, Method m, Object[] args) throws Throwable {
			// 获取输入值，对其进行处理，然后返回计算结果。
			String input = (String) args[0];
			...
			return ...;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes"]
----
	/**
	 * 用于覆盖 `MyValueCalculator` 中现有的 `computeValue(String)` 实现。
	 */
	class ReplacementComputeValue : MethodReplacer {

		override fun reimplement(obj: Any, method: Method, args: Array<out Any>): Any {
			// 获取输入值，对其进行处理，然后返回计算结果。
			val input = args[0] as String;
			...
			return ...;
		}
	}
----
======



用于部署原始类并指定方法覆写的 Bean 定义，示例如下：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="myValueCalculator" class="x.y.z.MyValueCalculator">
		<!-- arbitrary method replacement -->
		<replaced-method name="computeValue" replacer="replacementComputeValue">
			<arg-type>String</arg-type>
		</replaced-method>
	</bean>

	<bean id="replacementComputeValue" class="a.b.c.ReplacementComputeValue"/>
----

你可以在 `<replaced-method/>` 元素内使用一个或多个 `<arg-type/>`
元素，来指明被重写方法的方法签名。仅当方法被重载且类中存在多个变体时，才需要提供参数签名。为方便起见，参数的类型字
符串可以是完全限定类型名的子串。例如，以下写法都能匹配 `java.lang.String`：

[source,java,indent=0,subs="verbatim,quotes"]
----
	java.lang.String
	String
	Str
----

由于参数的数量通常足以区分每个可能的选择，这一快捷方式能让你只需键入与某个参数类型匹配的最短字符串，从而节省大量输入。
