[[beans-factory-properties-detailed]]
= 依赖与配置详解

如 xref:core/beans/dependencies/factory-collaborators.adoc[上一节] 中所述，
你可以将 bean 属性和构造函数参数定义为对其他受管 bean（协作者）的引用，或定义为内联定义的值。Spring 基于 XML
的配置元数据在其 `<property/>` 和 `<constructor-arg/>` 元素中支持子元素类型，以实现此目的。

[[beans-value-element]]
== 直接值（原始类型、字符串等）

`value` 属性用于将 `<property/>` 元素的属性或构造器参数指定为人类可读的字符串表示形式。Spring 的
xref:core/validation/convert.adoc#core-convert-ConversionService-API[转换服务] 用于将这些值从 `String`
转换为属性或参数的实际类型。以下示例展示了设置各种值的情况：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="myDataSource" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
		<!-- 去调用 `setDriverClassName(String)` 方法。 -->
		<property name="driverClassName" value="com.mysql.jdbc.Driver"/>
		<property name="url" value="jdbc:mysql://localhost:3306/mydb"/>
		<property name="username" value="root"/>
		<property name="password" value="misterkaoli"/>
	</bean>
----

以下示例使用 xref:core/beans/dependencies/factory-properties-detailed.adoc#beans-p-namespace[p-namespace]
以实现更简洁的 XML 配置：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:p="http://www.springframework.org/schema/p"
		xsi:schemaLocation="http://www.springframework.org/schema/beans
		https://www.springframework.org/schema/beans/spring-beans.xsd">

		<bean id="myDataSource" class="org.apache.commons.dbcp.BasicDataSource"
			destroy-method="close"
			p:driverClassName="com.mysql.jdbc.Driver"
			p:url="jdbc:mysql://localhost:3306/mydb"
			p:username="root"
			p:password="misterkaoli"/>

	</beans>
----

前面的 XML 更为简洁。然而，拼写错误会在运行时而非设计时被发现，除非你使用支持在创建 bean 定义时自动补全属性的 IDE（例如 https://www.jetbrains.com/idea/[IntelliJ IDEA] 或  {spring-site-tools}[Spring Tools] ）。强烈推荐使用此类 IDE 辅助工具。

你也可以配置一个 `java.util.Properties` 实例，如下所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="mappings"
		class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">

		<!-- 类型为 `java.util.Properties`-->
		<property name="properties">
			<value>
				jdbc.driver.className=com.mysql.jdbc.Driver
				jdbc.url=jdbc:mysql://localhost:3306/mydb
			</value>
		</property>
	</bean>
----
Spring container 会通过 JavaBeans `PropertyEditor` 机制，将 `<value/>` 元素内的文本转换为 `java.util.Properties` 实例。这是一种便捷的简写方式，也是 Spring 团队在少数几个地方更倾向于使用嵌套 `<value/>` 元素而非 `value` 属性风格的场景之一。

[[beans-idref-element]]
=== `idref` 元素

`idref` 元素是一种简单且不易出错的方式，用于将 container 中另一个 bean 的 `id`（字符串值——而非引用）传递给 `<constructor-arg/>` 或 `<property/>` 元素。以下示例展示了如何使用它：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="collaborator" class="..." />

	<bean id="client" class="...">
		<property name="targetName">
			<idref bean="collaborator" />
		</property>
	</bean>
----

前面的 bean 定义片段在运行时与以下片段完全等价：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="collaborator" class="..." />

	<bean id="client" class="...">
		<property name="targetName" value="collaborator" />
	</bean>
----

第一种形式优于第二种，因为使用 `idref` 标签可以让 container 在部署时验证所引用的命名 bean
确实存在。而在第二种变体中，传递给 `client` bean 的 `targetName`
属性的值不会进行任何验证。因此，拼写错误通常只有在 `client` bean
实际被实例化时才会被发现（且很可能导致致命结果）。如果 `client` bean 是一个
xref:core/beans/factory-scopes.adoc[prototype] bean，那么这种拼写错误及其引发的异常可能只有在 container 部署很久之后才会被发现。

NOTE: `<idref/>` 元素带来价值的一个常见场景（至少在 Spring 2.0 之前的版本中）是在 `ProxyFactoryBean` bean 定义中配置 xref:core/aop-api/pfb.adoc#aop-pfb-1[AOP interceptors]。在指定拦截器名称时使用 `<idref/>` 元素，可以避免拼错拦截器 ID。


[[beans-ref-element]]
== 引用其他 Bean（协作者）

`ref` 元素是 `<constructor-arg/>` 或 `<property/>` 定义元素内部的最后一个元素。在这里，您可以将 bean
的指定属性值设置为 container 所管理的另一个 bean（协作者）的引用。被引用的 bean 是其属性待设置的 bean
的一个依赖项，并且在设置属性之前会根据需要按需初始化。（如果协作者是单例 bean，则它可能已经由 container
初始化。）所有引用最终都是对另一个对象的引用。作用域和验证取决于您是通过 `bean` 或 `parent` 属性指定其他对象的 ID
还是名称。

通过 `bean` 标签的 `<ref/>` 属性来指定目标 bean 是最通用的形式，它允许创建对同一 container 或父 container 中任意
bean 的引用，无论该 bean 是否位于同一个 XML 文件中。`bean` 属性的值可以与目标 bean 的 `id` 属性相同，也可以与目标
bean 的 `name` 属性中的某个值相同。以下示例展示了如何使用 `ref` 元素：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<ref bean="someBean"/>
----

通过 `parent` 属性指定目标 bean，会创建对当前 container 父 container 中某个 bean 的引用。`parent`
属性的值可以与目标 bean 的 `id` 属性相同，也可以与目标 bean 的 `name` 属性中的某个值相同。目标 bean 必须位于当前
container 的父 container 中。这种 bean 引用变体主要应在以下场景中使用：当存在 container 层级结构，并且希望用与父
bean 同名的 proxy 来包装父 container 中的现有 bean 时。下面这对列表展示了如何使用 `parent` 属性：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<!-- in the parent context -->
	<bean id="accountService" class="com.something.SimpleAccountService">
		<!-- insert dependencies as required here -->
	</bean>
----

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<!-- 在子（后代）context 中，bean 名称与父 bean 相同。 -->
	<bean id="accountService" 
		class="org.springframework.aop.framework.ProxyFactoryBean">
		<property name="target">
			<ref parent="accountService"/> <!-- 注意我们是如何引用父 bean 的。 -->
		</property>
		<!-- 在此处按需插入其他配置和依赖项 -->
	</bean>
----

NOTE: `local` 元素上的 `ref` 属性在 4.0 beans XSD 中不再受支持，因为它不再比常规的 `bean` 引用提供更多价值。升级到
4.0 schema 时，请将现有的 `ref local` 引用更改为 `ref bean`。

[[beans-inner-beans]]
== 内部 bean

在 `<property/>` 或 `<constructor-arg/>` 元素内部，一个 `<bean/>` 元素定义了一个内部 bean，如下例所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="outer" class="...">
		<!-- 不要使用对目标 bean 的引用，而是直接内联定义目标 bean。 -->
		<property name="target">
			<bean class="com.example.Person"> <!-- 这是内部 bean。 -->
				<property name="name" value="Fiona Apple"/>
				<property name="age" value="25"/>
			</bean>
		</property>
	</bean>
----

内部 bean 定义不需要指定 ID 或名称。如果指定了，container 也不会将该值用作标识符。container 在创建时还会忽略
`scope` 标志，因为内部 bean 始终是匿名的，并且始终与外部 bean 一起创建。无法独立访问内部
bean，也无法将其注入到除封闭 bean 之外的其他协作 bean 中。

作为边界情况，自定义作用域有可能收到销毁回调——例如，单例 bean 中包含的请求作用域内部 bean。内部 bean
实例的创建与其所属 bean 绑定，但销毁回调使其能够参与请求作用域的生命周期。这并非常见场景。内部 bean
通常仅共享其所属 bean 的作用域。


[[beans-collection-elements]]
== 集合

`<list/>`、`<set/>`、`<map/>` 和 `<props/>` 元素分别设置 Java `Collection` 类型 `List`、`Set`、`Map` 和
`Properties` 的属性和参数。以下示例展示了如何使用它们：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="moreComplexObject" class="example.ComplexObject">
		<!-- 触发一次 `setAdminEmails(java.util.Properties)` 调用 -->
		<property name="adminEmails">
			<props>
				<prop key="administrator">administrator@example.org</prop>
				<prop key="support">support@example.org</prop>
				<prop key="development">development@example.org</prop>
			</props>
		</property>
		<!-- 触发一次 `setSomeList(java.util.List)` 调用 -->
		<property name="someList">
			<list>
				<value>a list element followed by a reference</value>
				<ref bean="myDataSource" />
			</list>
		</property>
		<!-- 触发一次 `setSomeMap(java.util.Map)` 调用 -->
		<property name="someMap">
			<map>
				<entry key="an entry" value="just some string"/>
				<entry key="a ref" value-ref="myDataSource"/>
			</map>
		</property>
		<!-- 触发一次 `setSomeSet(java.util.Set)` 调用 -->
		<property name="someSet">
			<set>
				<value>just some string</value>
				<ref bean="myDataSource" />
			</set>
		</property>
	</bean>
----

映射键或映射值，或集合值，也可以是以下任意元素：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	bean | ref | idref | list | set | map | props | value | null
----

[[beans-collection-elements-merging]]
=== 集合合并

Spring container 还支持集合的合并。应用程序开发者可以定义一个父级 `<list/>`、`<map/>`、`<set/>` 或 `<props/>`
元素，并让子级 `<list/>`、`<map/>`、`<set/>` 或 `<props/>` 元素继承并覆盖父集合中的值。也就是说，子集合的值是父集合与子集合元素合并的结果，其中子集合的元素会覆盖父集合中指定的值。

本节关于合并的内容讨论了父子 bean 机制。不熟悉父 bean 与子 bean 定义的读者，不妨先阅读
xref:core/beans/child-bean-definitions.adoc[相关章节] 再继续。

以下示例演示了集合合并：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans>
		<bean id="parent" abstract="true" class="example.ComplexObject">
			<property name="adminEmails">
				<props>
					<prop key="administrator">administrator@example.com</prop>
					<prop key="support">support@example.com</prop>
				</props>
			</property>
		</bean>
		<bean id="child" parent="parent">
			<property name="adminEmails">
				<!-- 合并操作在子集合定义中指定。 -->
				<props merge="true">
					<prop key="sales">sales@example.com</prop>
					<prop key="support">support@example.co.uk</prop>
				</props>
			</property>
		</bean>
	<beans>
----

请注意 `child` Bean 定义中 `adminEmails` 属性的 `<props/>` 元素上使用了 `merge=true` 属性。当 `child` bean 被 container
解析并实例化后，所得到的实例包含一个 `adminEmails` `Properties` 集合，该集合是子级 `adminEmails` 集合与父级 `adminEmails` 集合合并后的结果。以下列表展示了这一结果：

[literal,subs="verbatim,quotes"]
----
administrator=administrator@example.com
sales=sales@example.com
support=support@example.co.uk
----

子 `Properties` 集合的值集继承父 `<props/>` 的所有属性元素，并且子集合中 `support` 值的值会覆盖父集合中的对应值。
这种合并行为同样适用于 `<list/>`、`<map/>` 和 `<set/>` 集合类型。在 `<list/>` 元素的特定情况下，与 `List`
集合类型相关的语义（即 `ordered` 值集合的概念）得以保留。父级的值排在子级列表的所有值之前。对于 `Map`、`Set` 和
`Properties` 集合类型，不存在排序。因此，对于 container 内部使用的相关 `Map`、`Set` 和 `Properties`
实现类型所基于的集合类型，没有排序语义生效。

[[beans-collection-merge-limitations]]
=== 集合合并的限制

您不能合并不同类型的集合（例如 `Map` 和 `List`）。如果尝试这样做，会抛出相应的`Exception`。必须在较低层级的、继承的子定义上指定 `merge` 属性。在父级集合定义上指定 `merge`属性是多余的，并且不会产生预期的合并效果。

[[beans-collection-elements-strongly-typed]]
=== 强类型集合

得益于 Java 对泛型类型的支持，您可以使用强类型集合。 也就是说，可以声明一个 `Collection` 类型，使其仅能包含（例如）`String` 元素。如果您使用 Spring 将强类型的 `Collection` 依赖注入到 bean 中，您可以利用 Spring 的类型转换支持，使得强类型 `Collection` 实例中的元素在添加到 `Collection` 之前被转换为适当的类型。以下 Java 类和 bean 定义展示了如何实现：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes"]
----
	public class SomeClass {

		private Map<String, Float> accounts;

		public void setAccounts(Map<String, Float> accounts) {
			this.accounts = accounts;
		}
	}
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes"]
----
class SomeClass {
	lateinit var accounts: Map<String, Float>
}
----
======

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans>
		<bean id="something" class="x.y.SomeClass">
			<property name="accounts">
				<map>
					<entry key="one" value="9.99"/>
					<entry key="two" value="2.75"/>
					<entry key="six" value="3.99"/>
				</map>
			</property>
		</bean>
	</beans>
----

当 `accounts` bean 的 `something` 属性准备注入时，强类型 `Map<String, Float>`
的元素类型的泛型信息可通过反射获得。因此，Spring 的类型转换基础设施能够识别各个值元素为 `Float`
类型，并将字符串值（`9.99`、`2.75` 和 `3.99`）转换为实际的 `Float` 类型。


[[beans-null-element]]
== 空值与空字符串值

Spring 将属性等的空参数视为空的 `Strings`。以下基于 XML 的配置元数据片段将 `email` 属性设置为空的 `String` 值（""）。

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean class="ExampleBean">
		<property name="email" value=""/>
	</bean>
----

前面的示例等同于以下 Java 代码：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes"]
----
	exampleBean.setEmail("");
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes"]
----
	exampleBean.email = ""
----
======


`<null/>` 元素处理 `null` 值。以下示例展示了这一用法：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean class="ExampleBean">
		<property name="email">
			<null/>
		</property>
	</bean>
----

前面的配置等同于以下 Java 代码：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes"]
----
	exampleBean.setEmail(null);
----

Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,quotes"]
----
	exampleBean.email = null
----
======


[[beans-p-namespace]]
== 使用 p-namespace 的 XML 快捷方式

p-namespace 允许你使用 `bean` 元素的属性（而不是嵌套的 `<property/>` 元素）来描述属性值、协作 Bean，或两者兼有。

Spring 支持基于 XML Schema 定义的可扩展配置格式 xref:core/appendix/xsd-schemas.adoc[with namespaces]。 本章讨论的 `beans` 配置格式定义在 XML Schema 文档中。然而，p-namespace 并未在
XSD 文件中定义，它仅存在于 Spring 的核心中。

以下示例展示了两个 XML 片段（第一个使用
标准 XML 格式，第二个使用 p-namespace），它们解析为相同的结果：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:p="http://www.springframework.org/schema/p"
		xsi:schemaLocation="http://www.springframework.org/schema/beans
			https://www.springframework.org/schema/beans/spring-beans.xsd">

		<bean name="classic" class="com.example.ExampleBean">
			<property name="email" value="someone@somewhere.com"/>
		</bean>

		<bean name="p-namespace" class="com.example.ExampleBean"
			p:email="someone@somewhere.com"/>
	</beans>
----

该示例展示了在 bean 定义中，p-namespace 中名为 `email` 的属性。
这告诉 Spring 包含一个属性声明。如前所述，p-namespace 没有模式定义，因此您可以将属性名称设置为属性名。

接下来的示例包含两个额外的 bean 定义，它们都引用了另一个 bean：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:p="http://www.springframework.org/schema/p"
		xsi:schemaLocation="http://www.springframework.org/schema/beans
			https://www.springframework.org/schema/beans/spring-beans.xsd">

		<bean name="john-classic" class="com.example.Person">
			<property name="name" value="John Doe"/>
			<property name="spouse" ref="jane"/>
		</bean>

		<bean name="john-modern"
			class="com.example.Person"
			p:name="John Doe"
			p:spouse-ref="jane"/>

		<bean name="jane" class="com.example.Person">
			<property name="name" value="Jane Doe"/>
		</bean>
	</beans>
----

该示例不仅使用了 `p` 命名空间来设置属性值，还采用了一种特殊格式来声明属性引用。第一个 bean 定义通过 `<property name="spouse" ref="jane"/>` 创建了从 bean `john` 到 bean `jane` 的引用，而第二个 bean 定义则使用 `p:spouse-ref="jane"` 作为属性来实现完全相同的功能。在此情况下，`spouse` 是属性名，而 `-ref` 部分则表示这并非直接值，而是对另一个 bean 的引用。

NOTE: p-namespace 不如标准 XML 格式灵活。例如，声明属性引用的格式与以 `Ref` 结尾的属性存在冲突，而标准 XML 格式则没有此问题。我们建议您谨慎选择使用方式，并与团队成员沟通，以避免生成同时使用这三种方式的 XML 文档。


[[beans-c-namespace]]
== 使用 c-namespace 的 XML 快捷方式

类似于 xref:core/beans/dependencies/factory-properties-detailed.adoc#beans-p-namespace[使用 p-namespace 的 XML 快捷方式]，c-namespace 在 Spring 3.1 中引入，允许使用内联属性来配置构造函数参数，而不是嵌套的 `constructor-arg` 元素。

以下示例使用 `c:` 命名空间完成了与 xref:core/beans/dependencies/factory-collaborators.adoc#beans-constructor-injection[Constructor-based Dependency Injection] 相同的操作。

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:c="http://www.springframework.org/schema/c"
		xsi:schemaLocation="http://www.springframework.org/schema/beans
			https://www.springframework.org/schema/beans/spring-beans.xsd">

		<bean id="beanTwo" class="x.y.ThingTwo"/>
		<bean id="beanThree" class="x.y.ThingThree"/>

		<!-- traditional declaration with optional argument names -->
		<bean id="beanOne" class="x.y.ThingOne">
			<constructor-arg name="thingTwo" ref="beanTwo"/>
			<constructor-arg name="thingThree" ref="beanThree"/>
			<constructor-arg name="email" value="something@somewhere.com"/>
		</bean>

		<!-- c-namespace declaration with argument names -->
		<bean id="beanOne" class="x.y.ThingOne" c:thingTwo-ref="beanTwo"
			c:thingThree-ref="beanThree" c:email="something@somewhere.com"/>

	</beans>
----

`c:` 命名空间在按名称设置构造函数参数时，遵循与 `p:` 命名空间相同的约定（即使用尾部 `-ref` 表示 bean
引用）。同样地，尽管它未在 XSD 模式中定义（它存在于 Spring 核心内部），仍需要在 XML 文件中声明。

在极少数情况下，构造函数参数名称不可用（通常是因为字节码在编译时未使用 `-parameters`
标志），您可以回退到参数索引，如下所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<!-- c-namespace 索引声明 -->
	<bean id="beanOne" class="x.y.ThingOne" c:_0-ref="beanTwo" c:_1-ref="beanThree"
		c:_2="something@somewhere.com"/>
----

NOTE: 由于 XML 语法规则，索引表示法要求存在前导 `_`，因为 XML 属性名称不能以数字开头（即使某些 IDE 允许这样做）。对于 `<constructor-arg>` 元素，也有相应的索引表示法，但通常不常用，因为在那里简单的声明顺序通常就足够了。

实际上，构造函数解析xref:core/beans/dependencies/factory-collaborators.adoc#beans-factory-ctor-arguments-resolution[机制]在匹配参数方面相当高效，因此除非确实有必要，我们建议在整个配置中统一使用名称标注方式。


[[beans-compound-property-names]]
== 复合属性名

当您设置 Bean 属性时，可以使用复合或嵌套的属性名称，只要路径中除最终属性名外的所有组成部分都不是
`null`。请考虑以下 Bean 定义：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="something" class="things.ThingOne">
		<property name="fred.bob.sammy" value="123" />
	</bean>
----

`something` bean 具有一个 `fred` 属性，该属性包含一个 `bob` 属性，而 `bob` 属性又包含一个 `sammy` 属性，最终这个 `sammy` 属性被设置为 `123` 的值。为了使这一过程生效，在 bean 构造完成后，`something` 的 `fred` 属性和 `fred` 的 `bob` 属性不能为 `null`。否则，将抛出 `NullPointerException`。